"""Alembic migration script template."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9676121ee5fc'
down_revision = '20260206_vocabulary_meanings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_sessions_status', 'review_sessions', ['status'], unique=False)
    op.create_index('ix_review_sessions_user_started', 'review_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('generated_questions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_instance_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('meaning_input', 'fill_blank', 'multiple_choice', 'error_detection', name='questiontype'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='questiondifficulty'), nullable=False),
    sa.Column('question_variant', sa.String(), nullable=True),
    sa.Column('question_data', sa.JSON(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('answer_change_count', sa.Integer(), nullable=True),
    sa.Column('confusion_pair_group', sa.String(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_questions_confusion', 'generated_questions', ['confusion_pair_group'], unique=False)
    op.create_index(op.f('ix_generated_questions_question_instance_id'), 'generated_questions', ['question_instance_id'], unique=True)
    op.create_index('ix_generated_questions_session', 'generated_questions', ['session_id'], unique=False)
    op.create_index('ix_generated_questions_user_vocab', 'generated_questions', ['user_id', 'vocabulary_id'], unique=False)
    op.drop_index('ix_ai_practice_logs_practice_type', table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_practiced_at', table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_user_id', table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_vocabulary_id', table_name='ai_practice_logs')
    op.drop_index('ix_dictionary_cache_word', table_name='dictionary_cache')
    op.create_index('ix_dictionary_cache_word', 'dictionary_cache', ['word'], unique=False)
    op.drop_index('ix_review_histories_reviewed_at', table_name='review_histories')
    op.drop_index('ix_review_histories_user_id', table_name='review_histories')
    op.drop_index('ix_review_histories_vocabulary_id', table_name='review_histories')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_index('ix_vocabularies_next_review_date', table_name='vocabularies')
    op.drop_index('ix_vocabularies_user_id', table_name='vocabularies')
    op.drop_constraint('vocabulary_meanings_vocabulary_id_fkey', 'vocabulary_meanings', type_='foreignkey')
    op.create_foreign_key(None, 'vocabulary_meanings', 'vocabularies', ['vocabulary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocabulary_meanings', type_='foreignkey')
    op.create_foreign_key('vocabulary_meanings_vocabulary_id_fkey', 'vocabulary_meanings', 'vocabularies', ['vocabulary_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_vocabularies_user_id', 'vocabularies', ['user_id'], unique=False)
    op.create_index('ix_vocabularies_next_review_date', 'vocabularies', ['next_review_date'], unique=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_review_histories_vocabulary_id', 'review_histories', ['vocabulary_id'], unique=False)
    op.create_index('ix_review_histories_user_id', 'review_histories', ['user_id'], unique=False)
    op.create_index('ix_review_histories_reviewed_at', 'review_histories', ['reviewed_at'], unique=False)
    op.drop_index('ix_dictionary_cache_word', table_name='dictionary_cache')
    op.create_index('ix_dictionary_cache_word', 'dictionary_cache', ['word'], unique=True)
    op.create_index('ix_ai_practice_logs_vocabulary_id', 'ai_practice_logs', ['vocabulary_id'], unique=False)
    op.create_index('ix_ai_practice_logs_user_id', 'ai_practice_logs', ['user_id'], unique=False)
    op.create_index('ix_ai_practice_logs_practiced_at', 'ai_practice_logs', ['practiced_at'], unique=False)
    op.create_index('ix_ai_practice_logs_practice_type', 'ai_practice_logs', ['practice_type'], unique=False)
    op.drop_index('ix_generated_questions_user_vocab', table_name='generated_questions')
    op.drop_index('ix_generated_questions_session', table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_question_instance_id'), table_name='generated_questions')
    op.drop_index('ix_generated_questions_confusion', table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_index('ix_review_sessions_user_started', table_name='review_sessions')
    op.drop_index('ix_review_sessions_status', table_name='review_sessions')
    op.drop_table('review_sessions')
    # ### end Alembic commands ###
