"""Alembic migration script template."""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '118d4b8b5129'
down_revision = None
branch_labels = None
depends_on = None

# Define enums for PostgreSQL
user_role_enum = sa.Enum('ADMIN', 'USER', name='userrole')
difficulty_level_enum = sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel')
review_quality_enum = sa.Enum('AGAIN', 'HARD', 'GOOD', 'EASY', name='reviewquality')
practice_type_enum = sa.Enum('FLASHCARD', 'FILL_BLANK', 'MULTIPLE_CHOICE', 'SENTENCE_GENERATION', name='practicetype')


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types explicitly first (optional but safer in some cases)
    # However, create_table will handle it if we pass the enum object.
    
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vocabularies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example_sentence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty_level', difficulty_level_enum, nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('easiness_factor >= 1.3', name='ck_easiness_factor_min'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_user_vocabulary')
    )
    op.create_index(op.f('ix_vocabularies_next_review_date'), 'vocabularies', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_vocabularies_user_id'), 'vocabularies', ['user_id'], unique=False)
    op.create_index('ix_vocabularies_user_next_review', 'vocabularies', ['user_id', 'next_review_date'], unique=False)
    op.create_index('ix_vocabularies_user_word', 'vocabularies', ['user_id', 'word'], unique=False)
    op.create_table('ai_practice_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('practice_type', practice_type_enum, nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('practiced_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('time_spent_seconds >= 0', name='ck_practice_time_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_practice_logs_practice_type'), 'ai_practice_logs', ['practice_type'], unique=False)
    op.create_index(op.f('ix_ai_practice_logs_practiced_at'), 'ai_practice_logs', ['practiced_at'], unique=False)
    op.create_index('ix_ai_practice_logs_type_date', 'ai_practice_logs', ['practice_type', 'practiced_at'], unique=False)
    op.create_index('ix_ai_practice_logs_user_date', 'ai_practice_logs', ['user_id', 'practiced_at'], unique=False)
    op.create_index(op.f('ix_ai_practice_logs_user_id'), 'ai_practice_logs', ['user_id'], unique=False)
    op.create_index('ix_ai_practice_logs_vocab_date', 'ai_practice_logs', ['vocabulary_id', 'practiced_at'], unique=False)
    op.create_index(op.f('ix_ai_practice_logs_vocabulary_id'), 'ai_practice_logs', ['vocabulary_id'], unique=False)
    op.create_table('review_histories',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('review_quality', review_quality_enum, nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('time_spent_seconds >= 0', name='ck_time_spent_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_histories_reviewed_at'), 'review_histories', ['reviewed_at'], unique=False)
    op.create_index('ix_review_histories_user_date', 'review_histories', ['user_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_review_histories_user_id'), 'review_histories', ['user_id'], unique=False)
    op.create_index('ix_review_histories_user_vocab_date', 'review_histories', ['user_id', 'vocabulary_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_review_histories_vocabulary_id'), 'review_histories', ['vocabulary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_histories_vocabulary_id'), table_name='review_histories')
    op.drop_index('ix_review_histories_user_vocab_date', table_name='review_histories')
    op.drop_index(op.f('ix_review_histories_user_id'), table_name='review_histories')
    op.drop_index('ix_review_histories_user_date', table_name='review_histories')
    op.drop_index(op.f('ix_review_histories_reviewed_at'), table_name='review_histories')
    op.drop_table('review_histories')
    op.drop_index(op.f('ix_ai_practice_logs_vocabulary_id'), table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_vocab_date', table_name='ai_practice_logs')
    op.drop_index(op.f('ix_ai_practice_logs_user_id'), table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_user_date', table_name='ai_practice_logs')
    op.drop_index('ix_ai_practice_logs_type_date', table_name='ai_practice_logs')
    op.drop_index(op.f('ix_ai_practice_logs_practiced_at'), table_name='ai_practice_logs')
    op.drop_index(op.f('ix_ai_practice_logs_practice_type'), table_name='ai_practice_logs')
    op.drop_table('ai_practice_logs')
    op.drop_index('ix_vocabularies_user_word', table_name='vocabularies')
    op.drop_index('ix_vocabularies_user_next_review', table_name='vocabularies')
    op.drop_index(op.f('ix_vocabularies_user_id'), table_name='vocabularies')
    op.drop_index(op.f('ix_vocabularies_next_review_date'), table_name='vocabularies')
    op.drop_table('vocabularies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # Manually drop enum types
    user_role_enum.drop(op.get_bind(), checkfirst=False)
    difficulty_level_enum.drop(op.get_bind(), checkfirst=False)
    review_quality_enum.drop(op.get_bind(), checkfirst=False)
    practice_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
