"""Alembic migration script template."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc214a3c3c14'
down_revision = '70f2c389292a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_audios',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('tts_provider', sa.String(), nullable=False),
    sa.Column('voice', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_audios_vocabulary_id', 'vocabulary_audios', ['vocabulary_id'], unique=False)
    op.add_column('generated_questions', sa.Column('is_used', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('generated_questions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_questions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('generated_questions', 'is_used')
    op.drop_index('ix_vocabulary_audios_vocabulary_id', table_name='vocabulary_audios')
    op.drop_table('vocabulary_audios')
    # ### end Alembic commands ###
