"""Alembic migration script template."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cd551fbc9b'
down_revision = '16016a1fd6ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix: Add column with server_default to populate existing rows
    op.add_column('generated_questions', sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
    # Optional: Drop default if only needed for migration, but keeping it is fine.
    # op.alter_column('generated_questions', 'usage_count', server_default=None)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_questions', 'usage_count')
    # ### end Alembic commands ###
