"""Alembic migration script template."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f2c389292a'
down_revision = '869fd0c9a4e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('last_review_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'last_review_date')
    # ### end Alembic commands ###
